### ISSUE TITLE
libtiff-5.dll error

### ISSUE THREAD

**Issue by YasMakH** [choosehappy/QuickAnnotator#15]
Hi,
I followed the instructions of this recent tutorial ( http://www.andrewjanowczyk.com/tutorial-quick-annotator-for-tubule-segmentation/ ) to install quick annotator in an anaconda environment, but when I run QA.py,  I get an error about libtiff-5.dll not found. 
Any help ?

**Comment by tasvora** [comment]
Hi,
Sorry to hear you are having an issue.
What is your environment configuration like
Windows/Linux ??
Cuda ?
Can you send your console error log and your requirments.txt file 

Regards
Tasneem

**Comment by YasMakH** [comment]
I am using windows. following the tutorial instructions, I got cuda 11 ( using  nvidia-smi), so I followed with cuda_11, and  installed the corresponding requirements : 
    cd cuda_11 
    pip3 install -r requirements.txt

the error in the console is as following :

_(annotator) C:\QuickAnnotator>python QA.py
Config sections = ['common', 'flask', 'cuda', 'sqlalchemy', 'pooling', 'train_ae', 'train_tl', 'make_patches', 'make_embed', 'get_prediction', 'frontend', 'superpixel']
Traceback (most recent call last):
  File "QA.py", line 11, in <module>
    from QA_api import api,delete_image
  File "C:\QuickAnnotator\QA_api.py", line 21, in <module>
    from QA_utils import get_file_tail
  File "C:\QuickAnnotator\QA_utils.py", line 1, in <module>
    import torch
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\__init__.py", line 134, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\3055366\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\lib\libtiff-5.dll" or one of its dependencies._

**Comment by tasvora** [comment]
Can you please do a 
> pip freeze > env_requirements.txt 
This will generate a env_requirements.txt 
and please send us your env_requirements.txt file

**Comment by tasvora** [comment]
Hi 

Thanks for this , and it looks alright, but seems like there is an issue in your environment.
As I tried a brand new virtual environment and it works fine, and in your case the application is not even starting up.

Is there a possibility to create a new virtual environment and try this out? Are you already using a virtual environment ? 
we also do have a Docker file if you want to try it out with Docker.

**Comment by tasvora** [comment]
Hi 
Did it work ?

**Comment by YasMakH** [comment]
Unfortunately no. I repeated the process multiple times, on new environments, but still getting the same error related to libtiff-5.dll

**Comment by tasvora** [comment]
Is the error message the exact same ? and it occurs on run python QA.py?

**Comment by YasMakH** [comment]
> Is the error message the exact same ? and it occurs on run python QA.py?

Yes. It is exactly the same, and occurs when running QA.py.

**Comment by tasvora** [comment]
Just noticed you are using python 3.7 ? is it possible to upgrade to python 3.8. 

Also can you try the cpu version of pytorch and test it out

conda install pytorch torchvision torchaudio cpuonly -c pytorch
or 
pip3 install torch torchvision torchaudio

**Comment by YasMakH** [comment]
> C:\Users\3055366\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\lib\libtiff-5.dll

Yes. I upgraded to python 3.8 following the same steps, and it is working now.
Many thanks

**Comment by choosehappy** [comment]
Great, thanks for update!
