### ISSUE TITLE
Question on importing annotations using script

### ISSUE THREAD

**Issue by darshats** [choosehappy/QuickAnnotator#17]
Hi,
What should the mask image be like when importing pre-existing annotation via script? Looking at the code comment in the script:
#--- Negative class: [255,0,255], Positive class: [255,255,255], seen but unknown [0,0,255]
I created the base rgb image, and under mask folder in the same directory I placed the mask image. The mask image has magenta background (255,0,255) and white annotation (255,255,255). But when looking at the imported image, something seems to have gone wrong. 
I have attached my images here. Must be something simple I need change, hopefully!
![sample](https://user-images.githubusercontent.com/56063876/151565246-bc32b6f6-df03-4b7f-897d-5e74b8764007.png)
![sample_mask](https://user-images.githubusercontent.com/56063876/151565270-b38d2d1c-c784-4266-9097-13e2804b3ab2.png)

Thanks for your help!
Darshat

**Comment by choosehappy** [comment]
I quickly looked at the script you're referring to, and I'm close to 100% sure that there is a typo

The positive class should be [0,255,255], since it should be creating something like a bitwise mask indicating RGB  --- > [negative,positive,seen]

it should look something like this:

![image](https://user-images.githubusercontent.com/9681868/151599198-caf0f4cd-ddf5-4a14-be6f-ef505553eb24.png)

@tasvora can you take a closer look and update the script if needed?

**Comment by darshats** [comment]
Hello,
I made the change to generate correct mask but still there is a problem. The lines of code in the script are like this:
toupload = np.zeros((nrow,ncol,3),dtype=np.uint8)
        toupload[:,:,2]=255
        toupload[:,:,0]=(mask[:,:,0]==False)*255
        toupload[:,:,1]=(mask[:,:,0]>0)*255 #### ??

The last line is doubtful - it has the same semantics as the middle line i.e. if the R layer is non-zero then set the left hand side to 255. What is the expected toupload ? cant you just copy the mask into it?

**Comment by darshats** [comment]
This seems  to work - the opencv BGR format needs to be accounted for:
toupload[:,:,2]=255
        toupload[:,:,0]=(mask[:,:,2]>0)*255
        toupload[:,:,1]=(mask[:,:,1]>0)*255

**Comment by choosehappy** [comment]
yup, that would explain it

here is where we swap it back:

https://github.com/choosehappy/QuickAnnotator/blob/466c6aa1d9f16fd3f7e934658d9dd2e8eb93d89e/QA_api.py#L683

Apologies for the oversight!

Can you submit a pull request with the needed changes so we can provide the updated version to others?

**Comment by NdaAzr** [comment]
I am wondering how we can import the existing annotation to this platform. Is there any script available for this?

**Comment by choosehappy** [comment]
Yup, via scripting:

https://github.com/choosehappy/QuickAnnotator/blob/main/cli/import_annotations_cli.py
